version: '3'
volumes:
    redis_siigo_game:

services:
    redis:
        image: redis:7.0.0-alpine
        expose:
            - '6379'
        volumes:
            volumes:
                - redis_siigo_game:/var/lib/redis
        container_name: siigogame_redis
        command: >
            --requirepass 0606
    app:
        build: ./server
        image: dev/app-siigo-game
        expose: 
            - 3002
        ports:
            - 3002:3000
        depends_on:
            redis:
                condition: service_started