version: '3'
volumes:
    redisSiigoGame:

services:
    redis:
        image: redis:7.0.0-alpine
        expose:
            - '6379'
        volumes:
            -volumes:
            - redisSiigoGame:/var/lib/redis
        container_name: siigoGame_redis
        command: >
            --requirepass 0606
    app:
        # build: ./dev